//Next
import Head from 'next/head'

import MainPage  from './MainPage'

import Skill from '../components/Sections/Skill';
import Footer from '../components/Sections/Footer';
import Introduction from '../components/Sections/Introduction';

const App = () => {
  return (
    <>   
      <Head>
        <title>Žaneta Sabadka - portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainPage/>
        <Introduction />
        <Skill />
        <Footer />  
      </main>
    </>

  );
}

export default App;
